#!/bin/sh

########### Common

export REPO=/mnt/karramba
export PROGRAM_PATH=/mnt/opt
export CPIPELINE=/usr/pipeline
export CGRU=${PROGRAM_PATH}/cgru
export CGRU_LOCATION=${CGRU}
export CGRU_VERSION=1.6.5

########### Afanasy
	
export AF_ROOT=${CGRU}/afanasy
export PATH=${AF_ROOT}/bin:${CGRU}/software_setup/bin:${PATH}
export AF_PYTHON=${AF_ROOT}/bin:${AF_ROOT}/python
export HOUDINI_CGRU_PATH=${CGRU}/plugins/houdini
export PYTHONPATH=${AF_PYTHON}:${PYTHONPATH}

OSNAME=`uname`

if [ "$OSNAME" == "Linux" ]; 
    then

	#ALIASES
	alias katana="/mnt/opt/Katana1.1v6/katana"
	

	export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${CPIPELINE}/lib/openVDB/lib:${CPIPELINE}/lib/Field3D/lib

	export PATH=${CPIPELINE}/bin:${PROGRAM_PATH}/3delight/bin:${PROGRAM_PATH}/hfs/bin:${CGRU}/bin:${CGRU}/afanasy/bin:${PATH}
		
	export PYTHONPATH=${CGRU}/lib/python:${CPIPELINE}/com:${CPIPELINE}/lib/shotgun::${PYTHONPATH}
	

	
	########### HOUDINI
	#export HIH=${PROGRAM_PATH}/hfs/houdini
	export HFS=${PROGRAM_PATH}/hfs
	#export H=${HFS}
	#export HB=${H}/bin
	#export HDSO=${H}/dsolib
#	export HD=${H}/demo
	#export HH=${H}/houdini
	#export HHC=${HH}/config
	#export HT=${H}/toolkit
	#export HSB=${HH}/sbin 


	
	########### 3delight
	export DELIGHT=${PROGRAM_PATH}/3delight
	export LD_LIBRARY_PATH=${DELIGHT}/lib:${PROGRAM_PATH}/massive/bin:${LD_LIBRARY_PATH}
	export DL_SHADERS_PATH=${DELIGHT}/shaders
	export DL_SEARCH_PATH=${DELIGHT}/shaders
	export DL_DISPLAYS_PATH=${DELIGHT}/displays
	export DL_PROCEDURALS_PATH=/mnt/opt/massive/bin
	export SHADERDL_OPTIONS="-I ${DELIGHT}/include"
	
	########### realflow
	export RF_2012_PATH=/mnt/opt/realflow64_6.0.2.0085


fi

if [ "$OSNAME" == "Darwin" ]; 
    then
	echo $OSNAME

fi
